name: build-non-main
run-name: Build the game
on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          use-github-cache: false
